theme: jekyll-theme-architect
plugins:
  - jekyll-seo-tag

title: "Abid's Writing Portfolio"
description: "Blogs | Tutorials | Cheat sheets | Projects | Books | Career Guide"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
