theme: jekyll-theme-cayman

title: "Abid's Writing Portfolio"
description: "A collection of blogs, tutorials, cheat sheets, guides, projects, and books covering data analytics, machine learning, SQL, Python, natural language processing, large language models, artificial intelligence, machine learning operations, and career guidance."
