theme: jekyll-theme-architect
plugins:
  - jekyll-seo-tag

# Theme settings
show_downloads: false
google_analytics: G-PRQC1HFQ4G

# Collections
collections:
  pages:
    output: true
    permalink: /:collection/:name
