theme: jekyll-theme-architect
plugins:
  - jekyll-seo-tag

title: "Abid's Writing Portfolio"
description: "Blogs | Tutorials | Cheat sheets | Projects | Books | Career Guide"

# Theme settings
show_downloads: false
google_analytics: G-PRQC1HFQ4G

# Collections
collections:
  pages:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
