theme: jekyll-theme-architect
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO and Sitemap settings
url: https://abid.work
title: "Abid's Writing Portfolio"
description: "Technical Writing Portfolio: Blogs, Tutorials, Cheat Sheets, Projects, Books & Career Resources"

# Theme settings
show_downloads: false
google_analytics: G-PRQC1HFQ4G

# Collections and Sitemap settings
collections:
  pages:
    output: true
    permalink: /:collection/:name

# Clean URLs without .html extension and trailing slash
permalink: /:title
trailing_slash: false

