theme: jekyll-theme-architect
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO and Sitemap settings
url: https://abid.work
title: "Abid's Writing Portfolio"
description: "Explore expertly crafted blogs, step-by-step tutorials, quick-reference cheat sheets, immersive projects, detailed book reviews, and career resources—all focused on data and AI."

# Theme settings
show_downloads: false
google_analytics: G-PRQC1HFQ4G

# Clean URLs without .html extension and trailing slash
permalink: /:title
trailing_slash: false

