theme: jekyll-theme-architect
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO and Sitemap settings
url: "https://abid.work"
title: "Abid's Writing Portfolio"
description: "Technical Writing Portfolio: Blogs, Tutorials, Cheat Sheets, Projects, Books & Career Resources"

# Theme settings
show_downloads: false
google_analytics: G-PRQC1HFQ4G

# Collections and Sitemap settings
collections:
  pages:
    output: true
    permalink: /:collection/:name

# Sitemap configuration
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      sitemap: true
      changefreq: "monthly"
      priority: 0.5
      last_modified_at: null
  - scope:
      path: "pages"
      type: "pages"
    values:
      sitemap: true
      changefreq: "weekly"
      priority: 0.7
      last_modified_at: null
  - scope:
      path: "index.md"
    values:
      sitemap: true
      changefreq: "daily"
      priority: 1.0
      last_modified_at: null
  - scope:
      path: "assets/*"
    values:
      sitemap: false
  - scope:
      path: "_layouts/*"
    values:
      sitemap: false
